version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/app
hooks:
  AfterInstall:
   - location: bin/deploy.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: bin/start.sh
     timeout: 300
     runas: root
