version: '3'
services:

  postgresDev:
    image: postgres
    environment:
      POSTGRES_USER: nlwheat_usr
      POSTGRES_PASSWORD: "DevPassw0rd"
      POSTGRES_DB: nlwheat_db
    ports:
      - "15432:5432"

  postgresTest:
      image: postgres
      environment:
        POSTGRES_USER: nlwheat_usr
        POSTGRES_PASSWORD: "test"
        POSTGRES_DB: nlwheat_db
      ports:
        - "25432:5432"
