version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  node16_pg12:
    docker:
      - image: circleci/node:16
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: nlwheat_usr
          POSTGRES_PASSWORD: test
          POSTGRES_DB: nlwheat_db
    steps:
      - checkout
      - run: npm install
      - run: 
          command: npm test
          environment:
            DATABASE_URL: postgresql://nlwheat_usr:test@localhost:5432/nlwheat_db?schema=public
            NODE_ENV: test
            JWT_SECRET: test
      - coveralls/upload:
          verbose: true
workflows:
  test:
    jobs:
      - node16_pg12