version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  node16_pg12:
    docker:
      - image: circleci/node:16
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: nlwheat_usr
          POSTGRES_PASSWORD: test
          POSTGRES_DB: nlwheat_db
    steps:
      - checkout
      - run: npm install
      - run: 
          command: npm test
          environment:
            DATABASE_URL: postgresql://nlwheat_usr:test@localhost:5432/nlwheat_db?schema=public
            NODE_ENV: test
            JWT_SECRET: test
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: coverage
  aws_deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - run: 'echo pipeline.project.git_url: << pipeline.project.git_url >>'
      - run: 'echo pipeline.git.revision: << pipeline.git.revision >>'
      - run: 'echo AWS_REGION: ${AWS_DEFAULT_REGION}'
      - run: 'export GIT_REPOSITORY=$(echo << pipeline.project.git_url>> | sed "s/https:\/\/github.com\///g") && echo $GIT_REPOSITORY'
      - aws-cli/setup
      - run: |
          aws deploy create-deployment \
          --application-name nlw-heat-api \
          --deployment-group-name master \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --github-location repository=$(echo << pipeline.project.git_url>> | sed "s/https:\/\/github.com\///g"),commitId=<< pipeline.git.revision >>
workflows:
  version: 2
  test:
    jobs:
      - node16_pg12
  deploy:
    jobs:
      - aws_deploy