version: 2

jobs:
  test:
    docker:
      - image: node:16
      - image: postgres:12
        auth:
            username: nlwheat_usr
            password: test
        environment:
          POSTGRES_DB: nlwheat_db
    steps:
      - checkout
      - run: npm install
      - run: npm test
